test: Fix E2E tests

diff --git a/.github/workflows/test-e2e.yml b/.github/workflows/test-e2e.yml
--- a/.github/workflows/test-e2e.yml
+++ b/.github/workflows/test-e2e.yml
@@ -65,9 +65,9 @@ jobs:
           echo "Test case 1 failed. The check did not found forbidden dependencies" && exit 1
 
       - name: Test - Case 1 - Assert 2 failed
-        if: contains(fromJson(steps.test-01.outputs.report).message, 'Found 637 allowed, 110 forbidden and 1 dangerous licenses') == false
+        if: contains(fromJson(steps.test-01.outputs.report).message, 'Found 637 allowed, 110 forbidden and 1 dangerous dependencies') == false
         run: |
-          echo "Test case 1 failed. The check did not found 116 forbidden dependencies and 1 dangerous dependency" && exit 1
+          echo "Test case 1 failed. The check did not found 110 forbidden and 1 dangerous dependencies" && exit 1
 
       - name: Test - Case 2
         id: test-02
@@ -90,6 +90,6 @@ jobs:
           echo "Test case 2 failed. The check did not found warning dependencies" && exit 1
 
       - name: Test - Case 2 - Assert 2 failed
-        if: contains(fromJson(steps.test-02.outputs.report).message, '91 dependencies have forbidden licenses. 666 dependencies have dangerous licenses.') == false
+        if: contains(fromJson(steps.test-02.outputs.report).message, 'Found 27 allowed, 83 forbidden and 638 dangerous dependencies.') == false
         run: |
-          echo "Test case 2 failed. The check did not found 91 forbidden dependencies and 666 dangerous dependency" && exit 1    
+          echo "Test case 2 failed. The check did not found 83 forbidden and 638 dangerous dependencies" && exit 1    
